### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by vladi-strilets** [andreciornavei/strapi-plugin-validator#2]
I'm getting the next error: 
```
error Invalid flags supplied to RegExp constructor '-[a-z0-9]+)*$'
```

with this validator rule: 
```
"rules": {
    "slug": {
        "required": "Site slug is required",
        "regex:^[a-z0-9]+(?:-[a-z0-9]+)*$": "Wrong format"
    }
}
```

Any ideas? Thanks!

**Comment by andreciornavei** [comment]
Hello @vladi-strilets , sorry about late answer... i have been very busy.

The plugin key resolver splits the ":" character to separate the validator name from its rules... In this case, your regex contains a character ":" inside it, and the resolver was not prepared for this circumstance (a little bug).

Recently i had the same problem with a date time validator, when i was trying to validate a time pattern that separe hour and minute by the ":" character. I have been solved this problem some time ago, maybe your problem was solved too. But if your issue continue, please let me know, will not to be so hard to fix.

Thanks.
